# -*- coding: utf-8 -*-
"""Improvedvisualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fNui-Ncch2pwhKGP-BGJKtiiPtn2yPj5
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# Load data
housing = pd.read_csv("housing.csv")

st.title("Housing Data Dashboard")

# 1. Ocean proximity distribution
st.subheader("Number of Homes by Ocean Proximity")
ocean_counts = housing['ocean_proximity'].value_counts().reset_index()
ocean_counts.columns = ['ocean_proximity', 'count']

fig1 = px.bar(ocean_counts, x='ocean_proximity', y='count', color='ocean_proximity')
st.plotly_chart(fig1)

# 2. Population vs Households
st.subheader("Population vs Households")
fig2 = px.scatter(housing, x='population', y='households', opacity=0.5)
st.plotly_chart(fig2)

# 3. Box Plot (Improved Visualization)
st.subheader("House Prices by Ocean Proximity")
fig3 = px.box(housing, x='ocean_proximity', y='median_house_value', color='ocean_proximity')
fig3.update_layout(xaxis_tickangle=45)
st.plotly_chart(fig3)