# -*- coding: utf-8 -*-
"""loan.train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZSZzzkvvO1krtGfoYPeZhqNwcJQJwTMk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("Downloads/loanP.train.csv")
df.head() #Reading the dataset in a dataframe using pandas

df.head() # Look at few top rows by using the function head()

